### ISSUE TITLE
Home page wireframes

### ISSUE THREAD

**Issue by sschafft** [the-petting-zoo/petting-zoo-relaunch#14]
Build home page wireframes

**Key Questions:** 
- Are banners static or dynamic? 
- How many customer photos? 
- What data needs to be displayed on those photos? 
- How many featured products? 
- What data needs to be displayed on the featured products?
- What is the contact information needed for #18 ?

**Comment by jayperryworks** [comment]
Wireframe:

![home](https://user-images.githubusercontent.com/1044536/57408462-b7e78980-71b3-11e9-8d05-da2d40409b7a.png)

**Comment by sschafft** [comment]
Closing given this is done I believe.
