### ISSUE TITLE
Update Jekyll pipeline

### ISSUE THREAD

**Issue by sschafft** [the-petting-zoo/petting-zoo-relaunch#2]
- [ ] Update to use just Jekyll for sass and determine performance / if we need anything else
- [x] Look at what JS we will need and determine if we need a more robust pipeline
- [ ] Build whatever pipeline we need based on JS requirements

**Comment by jayperryworks** [comment]
Seeing a fair amount of JS we wrote for the original site, mostly to handle stuff like tabs and layout issues (e.g. making stuff the same height). A lot of this can be discarded and replaced with current CSS (e.g. flexbox, grid, etc.), but I'll add webpack anyway to handle the JS we do keep. Will be helpful to have babel, minification, etc. that comes with that.

**Comment by sschafft** [comment]
Sounds good to me.
