### ISSUE TITLE
Determine how to handle banner ads

### ISSUE THREAD

**Issue by sschafft** [the-petting-zoo/petting-zoo-relaunch#26]
It looks like there are a number of "banner ads" through out the site, it might be easier to handle this as a single content type that is referenced across the site. But that might add unnecessary complexity and it might be as-simple to just setup individual images depending on what is needed for banner ads.

**Comment by jayperryworks** [comment]
Yeah, good point. If we set up a basic `ad` content type, maybe there's metadata for where it should be displayed (e.g. `display: homepage \ weight: 1`), that might make future updates easier -- or at least give us more long term flexibility.

**Comment by jayperryworks** [comment]
This was resolved in the homepage wire framing session, and the changes we made in Sprint 3.
