### ISSUE TITLE
Refactor JS / Remove jQuery & Pluginsa

### ISSUE THREAD

**Issue by sschafft** [the-petting-zoo/petting-zoo-relaunch#30]
Refactor JS / Remove jQuery & Plugins because jQuery is sad and there are better alternatives these days. 

Related to #2

**Comment by jayperryworks** [comment]
I've set up the pipeline, etc. for the new JS but will need to refactor/replace scripts as we go. Most of the current scripts depend on the current markup, which will be changing (probably dramatically) over the next few sprints as we make layout updates and pull in new CSS.

Will keep referencing this issue as I replace each old script with the new version, and aim to resolve it by the end of our current SOW (~Sprint 5).
