### ISSUE TITLE
Deal with tags on blog posts / bad data in blog posts

### ISSUE THREAD

**Issue by sschafft** [the-petting-zoo/petting-zoo-relaunch#38]
- [x] Determine why there are tags
- [x] Determine if we need tags, and do something with them.
- [ ] Remove blog post drafts
- [ ] Remove blog posts that are not under "category blog post"
- [ ] Remove blog posts that are hidden

**Comment by sschafft** [comment]
@jayperryworks - it looksl ike there are tags on some blog posts, but not others, but nothing as far as I can tell is happening regardless of the tag as it stands now.

**Comment by jayperryworks** [comment]
Yes, AFAIK we're not doing anything with tags currently (e.g. category pages, etc.). That's not in our current SOW, so I'd suggest we leave the metadata so tags can be processed later if the client decides to use them.

**Comment by sschafft** [comment]
Yea it just impacts the CMS if we want to actually deal with them. Ie - what are the tags, how many, what options, is it auto-add (it cant be). So I'll just ignore it for now and we can talk to them tomorrow.

**Comment by sschafft** [comment]
@jayperryworks - I'm guessing we can just close this / talk to her about it once the CMS is up? And just say please prune your site?

**Comment by jayperryworks** [comment]
yeah, that makes sense. I can work with Jess and her team to clean up as needed, but I think we're okay on our end for the time being.
