### ISSUE TITLE
Refactor CSS

### ISSUE THREAD

**Issue by sschafft** [the-petting-zoo/petting-zoo-relaunch#6]
Refactor CSS so that the site design stays the same but follows an improved structure

- [x] color theming
- [x] typography
- [x] spacing
- [x] layout and grids
- [ ] rework UI components as needed

**Comment by jayperryworks** [comment]
Going to hold off on using any of the new CSS in templates right now; since we'll be making updates throughout the site, it makes more sense to pull in the new classes as we're refactoring markup.
