### ISSUE TITLE
Initial Designs [Product & Navigation]

### ISSUE THREAD

**Issue by sschafft** [the-petting-zoo/petting-zoo-relaunch#7]
- [x] Build wireframes for sub-navigation
- [x] Build wireframes for product pages / product content types

**Comment by jayperryworks** [comment]
Home page initial wireframe:

![home](https://user-images.githubusercontent.com/1044536/57395661-afcd2100-7196-11e9-81c3-d38b7df39aa8.png)

**Comment by jayperryworks** [comment]
## Wireframes:

Product page

![products](https://user-images.githubusercontent.com/1044536/57408517-d51c5800-71b3-11e9-861d-262985179935.png)

Catalog page

![catalog](https://user-images.githubusercontent.com/1044536/57408543-e2d1dd80-71b3-11e9-80b0-df09fe38088b.png)

Collection (tag) page
(same as catalog but no PDF download link)

![tag](https://user-images.githubusercontent.com/1044536/57408559-f2512680-71b3-11e9-93df-33b468206403.png)


Product details page

![details](https://user-images.githubusercontent.com/1044536/57408585-009f4280-71b4-11e9-9d52-09a1d446eb4a.png)
