### ISSUE TITLE
Catalog and collection dropdown are not populating with selections for products in the CMS

### ISSUE THREAD

**Issue by jayperryworks** [the-petting-zoo/petting-zoo-relaunch#90]
When you create a new product and select a catalog or collection from the dropdowns at the bottom, the items you select do not populate in the menu. 

The relationship does not seem to be established on save, either. Not sure what's going on, but seems to be some kind of bug with the ID/title display config there?

=== FIX ===
- Go through and add unique_ids
- Go through and remove any superflous content.

**Comment by HellyStoyanova** [comment]
![2019-05-17_13-45-33](https://user-images.githubusercontent.com/21204942/57946376-26aa9e00-78aa-11e9-881d-21e3295ed525.gif)

**Comment by HellyStoyanova** [comment]
The same is happening when adding catalog topics to catalog
![2019-05-21_15-23-03](https://user-images.githubusercontent.com/21204942/58124721-dc445c80-7bdc-11e9-9349-055fbdf441bd.gif)
